title: Conference Deadlines for wkblab
description: Countdowns to conference deadlines
author: Abhishek Das

domain: "kwakaba.github.io"
baseurl: "/ai-deadlines"

twitter_username: 
twitter_hashtag: 
github_username: kwakaba
github_repo: ai-deadlines

markdown: kramdown
ga_id: 

include: ['_pages']
